// Chat UI (core-only)

// Re-export everything from SDK
export {
  // Runtime
  AgentRuntime,
  // Provider config
  API_TYPES,
  type ApprovalRequest,
  // Skills
  addSkill,
  // Message utilities
  agentMessagesToChatMessages,
  applyProxyToModel,
  // Tools
  bashTool,
  // OAuth
  buildAuthorizationUrl,
  buildCustomModel,
  buildSkillsPromptSection,
  type ChatMessage,
  // Storage
  type ChatSession,
  configureNamespace,
  createSession,
  // Truncation
  DEFAULT_MAX_BYTES,
  DEFAULT_MAX_LINES,
  type Disposable,
  defineTool,
  // VFS
  deleteFile,
  deleteSession,
  deriveStats,
  // Lockdown
  ensureLockdown,
  exchangeOAuthCode,
  extractPartsFromAssistantMessage,
  type FetchProvider,
  type FetchResult,
  fetchWeb,
  fileExists,
  formatFingerprintCheckHook,
  formatFingerprintPreHook,
  formatFingerprintRecordHook,
  formatSize,
  generateId,
  generatePKCE,
  getBash,
  getFileType,
  getInstalledSkills,
  getNamespace,
  getOrCreateCurrentSession,
  getOrCreateDocumentId,
  getSession,
  getSessionMessageCount,
  getSharedCustomCommands,
  getVfs,
  HookRegistry,
  type HostApp,
  type ImageSearchOptions,
  type ImageSearchProvider,
  type ImageSearchResult,
  listFetchProviders,
  listImageSearchProviders,
  listSearchProviders,
  listSessions,
  listUploads,
  loadOAuthCredentials,
  loadPdfDocument,
  loadSavedConfig,
  loadVfsFiles,
  // Web
  loadWebConfig,
  type MessagePart,
  OAUTH_PROVIDERS,
  type OAuthCredentials,
  type OAuthFlowState,
  PatternRegistry,
  type PermissionMode,
  PlanManager,
  type ProviderConfig,
  parseSkillMeta,
  type ReasoningPattern,
  type RuntimeAdapter,
  type RuntimeState,
  readFile,
  readFileBuffer,
  readTool,
  refreshOAuthToken,
  removeOAuthCredentials,
  removeSkill,
  renameSession,
  resetVfs,
  resizeImage,
  restoreVfs,
  type ScopeRiskEstimate,
  type SearchOptions,
  type SearchProvider,
  type SearchResult,
  type SessionStats,
  type SkillInput,
  type SkillMeta,
  type StorageNamespace,
  // Sandbox
  sandboxedEval,
  saveConfig,
  saveOAuthCredentials,
  saveSession,
  saveVfsFiles,
  saveWebConfig,
  searchImages,
  searchWeb,
  setCustomCommands,
  setSkillFiles,
  setStaticFiles,
  snapshotVfs,
  stripEnrichment,
  syncSkillsToVfs,
  type TaskClassification,
  type TaskPhase,
  type TaskRecord,
  THINKING_LEVELS,
  type ThinkingLevel,
  type ToolCallStatus,
  type ToolResult,
  toBase64,
  toolError,
  toolSuccess,
  toolText,
  truncateHead,
  truncateTail,
  type UploadedFile,
  VerificationEngine,
  type VerificationSuite,
  type WebConfig,
  type WebContext,
  writeFile,
} from "@office-agents/sdk";
export type {
  AppAdapter,
  ChatTab,
  ToolExtrasProps,
} from "./chat";
export { ChatInterface, FilesPanel, getChatContext } from "./chat";
export { default as ErrorBoundary } from "./chat/error-boundary.svelte";
