export {
  type OfficeBridgeClientOptions,
  type OfficeBridgeController,
  startOfficeBridge,
} from "./client.js";
export {
  BRIDGE_PROTOCOL_VERSION,
  type BridgeApp,
  type BridgeClassifiedError,
  type BridgeError,
  type BridgeErrorClass,
  type BridgeEventMessage,
  type BridgeEventName,
  type BridgeEventPayloads,
  type BridgeHelloMessage,
  type BridgeHostInfo,
  type BridgeInvokeMessage,
  type BridgeInvokeMethod,
  type BridgeInvokeRequest,
  type BridgeResponseMessage,
  type BridgeRuntimeStateSlice,
  type BridgeSessionSnapshot,
  type BridgeStoredEvent,
  type BridgeToolDefinition,
  type BridgeToolExecutionResult,
  type BridgeTypedEvent,
  type BridgeVfsDeleteParams,
  type BridgeVfsEntry,
  type BridgeVfsListParams,
  type BridgeVfsReadParams,
  type BridgeVfsReadResult,
  type BridgeVfsWriteParams,
  type BridgeWelcomeMessage,
  type BridgeWireMessage,
  createBridgeEvent,
  createBridgeId,
  DEFAULT_BRIDGE_HOST,
  DEFAULT_BRIDGE_HTTP_URL,
  DEFAULT_BRIDGE_PORT,
  DEFAULT_BRIDGE_WS_PATH,
  DEFAULT_BRIDGE_WS_URL,
  DEFAULT_REQUEST_TIMEOUT_MS,
  extractToolError,
  extractToolImages,
  extractToolText,
  getDefaultRawExecutionTool,
  normalizeBridgeUrl,
  serializeForJson,
  toBridgeClassifiedError,
  toBridgeError,
  uint8ArrayToBase64,
} from "./protocol.js";
export { DOM_QUERIES } from "./dom-queries.js";
